#!/usr/bin/env bash
# =============================================================================
# fetch-template-docs.sh — mirror the template app's docs into the mdBook site
#
# The student template lives in its own repo (byu-ml-capstone/hello-world-app)
# and is gitignored here, so its READMEs cannot be symlinked into docs/src the
# way this repo's own guides are. Instead they are fetched at build time, which
# keeps ONE source of truth: edit the README in the template repo and the docs
# site picks it up on the next build. Nothing is copied into git.
#
# Run by .github/workflows/docs.yml before `mdbook build`. Safe to run locally
# if you want to preview the site (the generated files are gitignored).
#
# Usage:
#   ./scripts/fetch-template-docs.sh [--branch main]
# =============================================================================
set -euo pipefail

REPO="byu-ml-capstone/hello-world-app"
BRANCH="main"
[[ "${1:-}" == "--branch" ]] && BRANCH="$2"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEST="$(dirname "$SCRIPT_DIR")/docs/src"
RAW="https://raw.githubusercontent.com/$REPO/$BRANCH"

fetch() {
    local src="$1" out="$2" title="$3"
    echo "  $src -> docs/src/$out"
    curl -fsSL "$RAW/$src" -o "$DEST/$out.tmp" \
        || { echo "ERROR: could not fetch $RAW/$src" >&2; exit 1; }

    # Provenance banner: readers land here from the sidebar with no clue the
    # page is mirrored, and editing the copy would be a dead end.
    {
        echo "<!-- GENERATED by scripts/fetch-template-docs.sh — do not edit here. -->"
        echo "> **Mirrored from [\`$REPO\`](https://github.com/$REPO/blob/$BRANCH/$src)**"
        echo "> — the $title that ships in every student repo. Edit it there, not here."
        echo ""
        cat "$DEST/$out.tmp"
    } > "$DEST/$out"
    rm -f "$DEST/$out.tmp"
}

mkdir -p "$DEST"
echo "Mirroring template docs from $REPO@$BRANCH:"
fetch "README.md"           "template-app.md"       "app README"
fetch "terraform/README.md" "template-terraform.md" "Terraform lab README"

# The app README links to terraform/README.md relative to the template repo;
# inside the book that path does not exist, so point it at the mirrored page.
sed -i.bak 's|](terraform/README.md)|](template-terraform.md)|g' "$DEST/template-app.md"
rm -f "$DEST/template-app.md.bak"

echo "Done."
